8540-INFO-concurrency model: multi-thread
8540-INFO-masquerade (NAT) address: None
8540-INFO-passive ports: None
6116-INFO-concurrency model: multi-thread
6116-INFO-masquerade (NAT) address: None
6116-INFO-passive ports: None
6116-INFO-127.0.0.1:52143-[] FTP session opened (connect)
6116-INFO-127.0.0.1:52143-[vendor03@example.com] USER 'vendor03@example.com' logged in.
6116-INFO-127.0.0.1:52143-[vendor03@example.com] FTP session closed (disconnect).
6116-INFO-127.0.0.1:52158-[] FTP session opened (connect)
6116-INFO-127.0.0.1:52158-[vendor06@example.com] USER 'vendor06@example.com' logged in.
6116-INFO-127.0.0.1:52165-[] FTP session opened (connect)
6116-INFO-127.0.0.1:52165-[] USER 'anonymous' failed login.
6116-INFO-127.0.0.1:52165-[] FTP session closed (disconnect).
6116-INFO-127.0.0.1:52172-[] FTP session opened (connect)
6116-INFO-127.0.0.1:52172-[vendor06@example.com] USER 'vendor06@example.com' logged in.
6116-INFO-127.0.0.1:52172-[vendor06@example.com] CWD A:\code\Current\dj\core\ftp\ftp_folders\vendor06@example.com 250
6116-INFO-127.0.0.1:52172-[vendor06@example.com] STOR A:\code\Current\dj\core\ftp\ftp_folders\vendor06@example.com\operation_807074450355.pdf completed=1 bytes=19855 seconds=0.0
6116-ERROR-unhandled exception in instance <DTPHandler(id=2420527288528, addr='127.0.0.1:52172', user='vendor06@example.com', sending-file=<_io.BufferedWriter name='A:\\code\\Current\\dj\\core\\ftp\\ftp_folders\\vendor06@example.com\\operation_807074450355.pdf'>, bytes-trans=19855)>
Traceback (most recent call last):
  File "C:\Users\devvr\AppData\Local\Programs\Python\Python38\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Users\devvr\AppData\Local\Programs\Python\Python38\lib\site-packages\pyftpdlib\handlers.py", line 796, in handle_read
    chunk = self.recv(self.ac_in_buffer_size)
  File "C:\Users\devvr\AppData\Local\Programs\Python\Python38\lib\site-packages\pyftpdlib\ioloop.py", line 915, in recv
    self.handle_close()
  File "C:\Users\devvr\AppData\Local\Programs\Python\Python38\lib\site-packages\pyftpdlib\handlers.py", line 885, in handle_close
    self.close()
  File "C:\Users\devvr\AppData\Local\Programs\Python\Python38\lib\site-packages\pyftpdlib\handlers.py", line 916, in close
    self.cmd_channel.on_file_received(filename)
  File "a:\code\Current\dj\core\ftp\tempCodeRunnerFile.py", line 100, in on_file_received
    content = json.loads(responce.content)
  File "C:\Users\devvr\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\devvr\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\devvr\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
6116-INFO-127.0.0.1:52172-[vendor06@example.com] FTP session closed (disconnect).
6116-INFO-127.0.0.1:52187-[] FTP session opened (connect)
6116-INFO-127.0.0.1:52187-[vendor06@example.com] USER 'vendor06@example.com' logged in.
6116-INFO-127.0.0.1:52187-[vendor06@example.com] CWD A:\code\Current\dj\core\ftp\ftp_folders\vendor06@example.com 250
6116-INFO-127.0.0.1:52187-[vendor06@example.com] STOR A:\code\Current\dj\core\ftp\ftp_folders\vendor06@example.com\PEAR.csv completed=1 bytes=56686 seconds=0.0
6116-ERROR-unhandled exception in instance <DTPHandler(id=2420527271840, addr='127.0.0.1:52187', user='vendor06@example.com', sending-file=<_io.BufferedWriter name='A:\\code\\Current\\dj\\core\\ftp\\ftp_folders\\vendor06@example.com\\PEAR.csv'>, bytes-trans=56686)>
Traceback (most recent call last):
  File "C:\Users\devvr\AppData\Local\Programs\Python\Python38\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Users\devvr\AppData\Local\Programs\Python\Python38\lib\site-packages\pyftpdlib\handlers.py", line 796, in handle_read
    chunk = self.recv(self.ac_in_buffer_size)
  File "C:\Users\devvr\AppData\Local\Programs\Python\Python38\lib\site-packages\pyftpdlib\ioloop.py", line 915, in recv
    self.handle_close()
  File "C:\Users\devvr\AppData\Local\Programs\Python\Python38\lib\site-packages\pyftpdlib\handlers.py", line 885, in handle_close
    self.close()
  File "C:\Users\devvr\AppData\Local\Programs\Python\Python38\lib\site-packages\pyftpdlib\handlers.py", line 916, in close
    self.cmd_channel.on_file_received(filename)
  File "a:\code\Current\dj\core\ftp\tempCodeRunnerFile.py", line 100, in on_file_received
    content = json.loads(responce.content)
  File "C:\Users\devvr\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\devvr\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\devvr\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
